/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.PersonalDetails;

/**
 *
 * @author deepv
 */
public class CreationPanel extends javax.swing.JPanel {

    PersonalDetails personalDetails;
    /**
     * Creates new form NewJPanel
     */
    public CreationPanel(PersonalDetails personalDetails) {
        initComponents();
        this.personalDetails = personalDetails;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jSubPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblTeleNos = new javax.swing.JLabel();
        lblFaxNo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblMedicalRecNum = new javax.swing.JLabel();
        lblHealthPlanNum = new javax.swing.JLabel();
        lblBankAcc = new javax.swing.JLabel();
        lblLicenseNo = new javax.swing.JLabel();
        lblVehicleIden = new javax.swing.JLabel();
        lblDeviceIden = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblIpAddress = new javax.swing.JLabel();
        lblBiometric = new javax.swing.JLabel();
        lblFacePhoto = new javax.swing.JLabel();
        lblUniqueIden = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeoData = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtTeleNos = new javax.swing.JTextField();
        txtFaxNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtMedicalRecNum = new javax.swing.JTextField();
        txtHealthPlanNum = new javax.swing.JTextField();
        txtBankAcc = new javax.swing.JTextField();
        txtLicenseNo = new javax.swing.JTextField();
        txtVehicleIden = new javax.swing.JTextField();
        txtDeviceIden = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtIpAddress = new javax.swing.JTextField();
        txtBiometric = new javax.swing.JTextField();
        txtUniqueIden = new javax.swing.JTextField();
        btnBrowseImg = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        llblCreate = new javax.swing.JLabel();

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name:");

        lblGeoData.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblGeoData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGeoData.setText("Geographic data:");

        lblDob.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblDob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDob.setText("Date of birth:");

        lblTeleNos.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblTeleNos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeleNos.setText("Telephone numbers:");

        lblFaxNo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblFaxNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFaxNo.setText("FAX number:");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email addresses:");

        lblSsn.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblSsn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSsn.setText("Social Security number:");

        lblMedicalRecNum.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblMedicalRecNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicalRecNum.setText("Medical record number:");

        lblHealthPlanNum.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblHealthPlanNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHealthPlanNum.setText("Health plan beneficiary number:");

        lblBankAcc.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblBankAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBankAcc.setText("Bank account numbers:");

        lblLicenseNo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblLicenseNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLicenseNo.setText("Certificate/license number:");

        lblVehicleIden.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblVehicleIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicleIden.setText("Vehicle identifiers and serial numbers including license plates:");

        lblDeviceIden.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblDeviceIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeviceIden.setText("Internet protocol addresses:");

        lblLinkedIn.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblLinkedIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLinkedIn.setText("Biometric identifiers (i.e. retinal scan, fingerprints):");

        lblIpAddress.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblIpAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIpAddress.setText("Device identifiers and serial numbers:");

        lblBiometric.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblBiometric.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBiometric.setText("LinkedIn:");

        lblFacePhoto.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblFacePhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacePhoto.setText("Full face photos and comparable images:");

        lblUniqueIden.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblUniqueIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUniqueIden.setText("Any unique identifying number, characteristic, or code:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });

        txtSsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsnActionPerformed(evt);
            }
        });

        btnBrowseImg.setText("Browse Image");
        btnBrowseImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSubPanelLayout = new javax.swing.GroupLayout(jSubPanel);
        jSubPanel.setLayout(jSubPanelLayout);
        jSubPanelLayout.setHorizontalGroup(
            jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSubPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGeoData)
                    .addComponent(lblName)
                    .addComponent(lblDob)
                    .addComponent(lblTeleNos)
                    .addComponent(lblFaxNo)
                    .addComponent(lblEmail)
                    .addComponent(lblSsn)
                    .addComponent(lblMedicalRecNum)
                    .addComponent(lblHealthPlanNum)
                    .addComponent(lblBankAcc)
                    .addComponent(lblLicenseNo)
                    .addComponent(lblVehicleIden)
                    .addComponent(lblIpAddress)
                    .addComponent(lblBiometric)
                    .addComponent(lblDeviceIden)
                    .addComponent(lblLinkedIn)
                    .addComponent(lblFacePhoto)
                    .addComponent(lblUniqueIden))
                .addGap(18, 18, 18)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(txtGeoData)
                    .addComponent(txtDob)
                    .addComponent(txtTeleNos)
                    .addComponent(txtFaxNo)
                    .addComponent(txtEmail)
                    .addComponent(txtSsn)
                    .addComponent(txtMedicalRecNum)
                    .addComponent(txtHealthPlanNum)
                    .addComponent(txtBankAcc)
                    .addComponent(txtLicenseNo)
                    .addComponent(txtVehicleIden)
                    .addComponent(txtDeviceIden)
                    .addComponent(txtLinkedin)
                    .addComponent(txtIpAddress)
                    .addComponent(txtBiometric)
                    .addComponent(txtUniqueIden, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(btnBrowseImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        jSubPanelLayout.setVerticalGroup(
            jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSubPanelLayout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblGeoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblTeleNos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblFaxNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblMedicalRecNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblHealthPlanNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblBankAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblLicenseNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14)
                        .addComponent(lblVehicleIden, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lblIpAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblBiometric, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblDeviceIden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblLinkedIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(jSubPanelLayout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtTeleNos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtMedicalRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtHealthPlanNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtVehicleIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtDeviceIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtIpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSubPanelLayout.createSequentialGroup()
                        .addComponent(lblFacePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(lblUniqueIden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jSubPanelLayout.createSequentialGroup()
                        .addComponent(btnBrowseImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(txtUniqueIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );

        jScrollPane.setViewportView(jSubPanel);

        btnSave.setText("Save Changes");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        llblCreate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        llblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llblCreate.setText("Create Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
            .addComponent(llblCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(llblCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtSsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSsnActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        personalDetails.setName(txtName.getText());
        personalDetails.setGeoData(txtGeoData.getText());
        personalDetails.setDob(txtDob.getText());
        personalDetails.setTeleNos(txtTeleNos.getText());
        personalDetails.setFaxNo(txtFaxNo.getText());
        personalDetails.setEmail(txtEmail.getText());
        personalDetails.setSsn(txtSsn.getText());
        personalDetails.setMedicalRecNum(txtMedicalRecNum.getText());
        personalDetails.setHealthPlanNum(txtHealthPlanNum.getText());
        personalDetails.setBankAcc(txtBankAcc.getText());
        personalDetails.setLicenseNo(txtLicenseNo.getText());
        personalDetails.setVehicleIden(txtVehicleIden.getText());
        personalDetails.setDeviceIden(txtDeviceIden.getText());
        personalDetails.setLinkedIn(txtLinkedin.getText());
        personalDetails.setIpAddress(txtIpAddress.getText());
        personalDetails.setBiometric(txtBiometric.getText());
//        personalDetails.setFacePhoto(txtFacePhoto.getText());
        personalDetails.setUniqueIden(txtUniqueIden.getText());
        
        JOptionPane.showMessageDialog(this, "Changes have been saved.");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBrowseImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseImgActionPerformed
        JFileChooser browseimage = new JFileChooser();
        int showDialogue = browseimage.showOpenDialog(null);
        
        if(showDialogue == JFileChooser.APPROVE_OPTION){
            File file = browseimage.getSelectedFile();
            String selectedImagePath = file.getAbsolutePath();
            JOptionPane.showConfirmDialog(this, "Image selected successfully!");
            personalDetails.setFacePhoto(selectedImagePath);
        }
    }//GEN-LAST:event_btnBrowseImgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseImg;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPanel jSubPanel;
    private javax.swing.JLabel lblBankAcc;
    private javax.swing.JLabel lblBiometric;
    private javax.swing.JLabel lblDeviceIden;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFacePhoto;
    private javax.swing.JLabel lblFaxNo;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHealthPlanNum;
    private javax.swing.JLabel lblIpAddress;
    private javax.swing.JLabel lblLicenseNo;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalRecNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTeleNos;
    private javax.swing.JLabel lblUniqueIden;
    private javax.swing.JLabel lblVehicleIden;
    private javax.swing.JLabel llblCreate;
    private javax.swing.JTextField txtBankAcc;
    private javax.swing.JTextField txtBiometric;
    private javax.swing.JTextField txtDeviceIden;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealthPlanNum;
    private javax.swing.JTextField txtIpAddress;
    private javax.swing.JTextField txtLicenseNo;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalRecNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTeleNos;
    private javax.swing.JTextField txtUniqueIden;
    private javax.swing.JTextField txtVehicleIden;
    // End of variables declaration//GEN-END:variables
}
