/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import model.PersonalDetails;

/**
 *
 * @author deepv
 */
public class DisplayPanel extends javax.swing.JPanel {

    PersonalDetails personalDetails;
    int width;

    /**
     * Creates new form NewJPanel
     */
    public DisplayPanel(PersonalDetails personalDetails) {
        initComponents();
        width = lblBiometricImg.getWidth();
        this.personalDetails = personalDetails;
        displayPersonalDetails();
        displayImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jSubPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblTeleNos = new javax.swing.JLabel();
        lblFaxNo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblMedicalRecNum = new javax.swing.JLabel();
        lblHealthPlanNum = new javax.swing.JLabel();
        lblBankAcc = new javax.swing.JLabel();
        lblLicenseNo = new javax.swing.JLabel();
        lblVehicleIden = new javax.swing.JLabel();
        lblDeviceIden = new javax.swing.JLabel();
        lblIpAddress = new javax.swing.JLabel();
        lblBiometric = new javax.swing.JLabel();
        lblUniqueIden = new javax.swing.JLabel();
        lblBiometricImg = new javax.swing.JLabel();
        lblImageDesc = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblBiometricIDesc = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeoData = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtTeleNos = new javax.swing.JTextField();
        txtFaxNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtMedicalRecNum = new javax.swing.JTextField();
        txtHealthPlanNum = new javax.swing.JTextField();
        txtBankAcc = new javax.swing.JTextField();
        txtLicenseNo = new javax.swing.JTextField();
        txtVehicleIden = new javax.swing.JTextField();
        txtDeviceIden = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtIpAddress = new javax.swing.JTextField();
        txtUniqueIden = new javax.swing.JTextField();
        llblCreate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 248, 248));

        jScrollPane.setBackground(new java.awt.Color(248, 248, 248));
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jSubPanel.setBackground(new java.awt.Color(248, 248, 248));

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name:");

        lblGeoData.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblGeoData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGeoData.setText("Geographic data:");

        lblDob.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblDob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDob.setText("Date of birth:");

        lblTeleNos.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblTeleNos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeleNos.setText("Telephone numbers:");

        lblFaxNo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblFaxNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFaxNo.setText("FAX number:");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email addresses:");

        lblSsn.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblSsn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSsn.setText("Social Security number:");

        lblMedicalRecNum.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblMedicalRecNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicalRecNum.setText("Medical record number:");

        lblHealthPlanNum.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblHealthPlanNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHealthPlanNum.setText("Health plan beneficiary number:");

        lblBankAcc.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblBankAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBankAcc.setText("Bank account numbers:");

        lblLicenseNo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblLicenseNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLicenseNo.setText("Certificate/license number:");

        lblVehicleIden.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblVehicleIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicleIden.setText("Vehicle identifiers and serial numbers including license plates:");

        lblDeviceIden.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblDeviceIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeviceIden.setText("Internet protocol addresses:");

        lblIpAddress.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblIpAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIpAddress.setText("Device identifiers and serial numbers:");

        lblBiometric.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblBiometric.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBiometric.setText("LinkedIn:");

        lblUniqueIden.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblUniqueIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUniqueIden.setText("Any unique identifying number, characteristic, or code:");

        lblImageDesc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        lblImageDesc.setText("Face Photo");

        lblBiometricIDesc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        lblBiometricIDesc.setText("Biometric");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSubPanelLayout = new javax.swing.GroupLayout(jSubPanel);
        jSubPanel.setLayout(jSubPanelLayout);
        jSubPanelLayout.setHorizontalGroup(
            jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSubPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGeoData)
                    .addComponent(lblName)
                    .addComponent(lblDob)
                    .addComponent(lblTeleNos)
                    .addComponent(lblFaxNo)
                    .addComponent(lblEmail)
                    .addComponent(lblSsn)
                    .addComponent(lblMedicalRecNum)
                    .addComponent(lblHealthPlanNum)
                    .addComponent(lblBankAcc)
                    .addComponent(lblLicenseNo)
                    .addComponent(lblVehicleIden)
                    .addComponent(lblIpAddress)
                    .addComponent(lblBiometric)
                    .addComponent(lblDeviceIden)
                    .addComponent(lblUniqueIden))
                .addGap(18, 18, 18)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSubPanelLayout.createSequentialGroup()
                        .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeleNos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicleIden, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jSubPanelLayout.createSequentialGroup()
                                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedicalRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHealthPlanNum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(lblBiometricImg, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jSubPanelLayout.createSequentialGroup()
                        .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeviceIden, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUniqueIden, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSubPanelLayout.createSequentialGroup()
                        .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jSubPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblImageDesc))
                            .addGroup(jSubPanelLayout.createSequentialGroup()
                                .addComponent(txtBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(lblBiometricIDesc)
                                .addGap(0, 1, Short.MAX_VALUE)))
                        .addGap(291, 291, 291))))
            .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSubPanelLayout.createSequentialGroup()
                    .addContainerGap(570, Short.MAX_VALUE)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(247, 247, 247)))
        );
        jSubPanelLayout.setVerticalGroup(
            jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSubPanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(lblImageDesc)
                .addGap(18, 18, 18)
                .addComponent(lblBiometricImg, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBiometricIDesc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSubPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeleNos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeleNos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicalRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealthPlanNum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHealthPlanNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleIden, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVehicleIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeviceIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceIden, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniqueIden, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUniqueIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(256, 256, 256))
            .addGroup(jSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jSubPanelLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(686, Short.MAX_VALUE)))
        );

        jSubPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBankAcc, lblDeviceIden, lblDob, lblEmail, lblFaxNo, lblGeoData, lblHealthPlanNum, lblIpAddress, lblLicenseNo, lblMedicalRecNum, lblName, lblSsn, lblTeleNos, lblUniqueIden, lblVehicleIden});

        jScrollPane.setViewportView(jSubPanel);

        llblCreate.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        llblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llblCreate.setText("View Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(llblCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(llblCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPanel jSubPanel;
    private javax.swing.JLabel lblBankAcc;
    private javax.swing.JLabel lblBiometric;
    private javax.swing.JLabel lblBiometricIDesc;
    private javax.swing.JLabel lblBiometricImg;
    private javax.swing.JLabel lblDeviceIden;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaxNo;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHealthPlanNum;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImageDesc;
    private javax.swing.JLabel lblIpAddress;
    private javax.swing.JLabel lblLicenseNo;
    private javax.swing.JLabel lblMedicalRecNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTeleNos;
    private javax.swing.JLabel lblUniqueIden;
    private javax.swing.JLabel lblVehicleIden;
    private javax.swing.JLabel llblCreate;
    private javax.swing.JTextField txtBankAcc;
    private javax.swing.JTextField txtDeviceIden;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealthPlanNum;
    private javax.swing.JTextField txtIpAddress;
    private javax.swing.JTextField txtLicenseNo;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalRecNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTeleNos;
    private javax.swing.JTextField txtUniqueIden;
    private javax.swing.JTextField txtVehicleIden;
    // End of variables declaration//GEN-END:variables

    private void displayPersonalDetails() {
        
        // call method to read data from personal details instance and set it to the txtFields
        setValuesToTxtBox(personalDetails);
    }

    /**
     * method to display selected image
     */
    private void displayImage() {
        ImageIcon image = new ImageIcon(personalDetails.getFacePhoto());
        Image resizedImage = image.getImage().getScaledInstance(149, 151, Image.SCALE_SMOOTH);
        lblBiometricImg.setIcon(new ImageIcon(resizedImage));
    }

    /**
     * Convert Date to string
     *
     * @param date
     * @return
     */
    private String dateToStringConverter(Date date) {
        String dateString;
        DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd");
        dateString = dateFormat.format(date);
        return dateString;
    }

    /**
     * This method reads the data from personalDetails object and sets it to the
     * txtFields so that it can be viewed
     *
     * @param personalDetails
     */
    private void setValuesToTxtBox(PersonalDetails personalDetails) {
        txtName.setText(personalDetails.getName());
        txtGeoData.setText(personalDetails.getGeoData());
        txtDob.setText(dateToStringConverter(personalDetails.getDob()));
        txtTeleNos.setText(personalDetails.getTeleNos());
        txtFaxNo.setText(personalDetails.getFaxNo());
        txtEmail.setText(personalDetails.getEmail());
        txtSsn.setText(personalDetails.getSsn());
        txtMedicalRecNum.setText(personalDetails.getMedicalRecNum());
        txtHealthPlanNum.setText(personalDetails.getHealthPlanNum());
        txtBankAcc.setText(personalDetails.getBankAcc());
        txtLicenseNo.setText(personalDetails.getLicenseNo());
        txtVehicleIden.setText(personalDetails.getVehicleIden());
        txtDeviceIden.setText(personalDetails.getDeviceIden());
        txtLinkedin.setText(personalDetails.getLinkedIn());
        txtIpAddress.setText(personalDetails.getIpAddress());
        txtUniqueIden.setText(personalDetails.getUniqueIden());
    }
}
