/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.PersonalDetails;

/**
 *
 * @author deepv
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel(PersonalDetails personalDetails) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblTeleNos = new javax.swing.JLabel();
        lblFaxNo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblMedicalRecNum = new javax.swing.JLabel();
        lblHealthPlanNum = new javax.swing.JLabel();
        lblBankAcc = new javax.swing.JLabel();
        lblLicenseNo = new javax.swing.JLabel();
        lblVehicleIden = new javax.swing.JLabel();
        lblDeviceIden = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblIpAddress = new javax.swing.JLabel();
        lblBiometric = new javax.swing.JLabel();
        lblUniqueIden = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeoData = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtTeleNos = new javax.swing.JTextField();
        txtFaxNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtMedicalRecNum = new javax.swing.JTextField();
        txtHealthPlanNum = new javax.swing.JTextField();
        txtBankAcc = new javax.swing.JTextField();
        txtLicenseNo = new javax.swing.JTextField();
        txtVehicleIden = new javax.swing.JTextField();
        txtDeviceIden = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtIpAddress = new javax.swing.JTextField();
        txtBiometric = new javax.swing.JTextField();
        txtUniqueIden = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        lblImageDesc = new javax.swing.JLabel();
        lblBiometricImage = new javax.swing.JLabel();
        lblBiometricDesc = new javax.swing.JLabel();
        llblCreate = new javax.swing.JLabel();

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name:");

        lblGeoData.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblGeoData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGeoData.setText("Geographic data:");

        lblDob.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblDob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDob.setText("Date of birth:");

        lblTeleNos.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblTeleNos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeleNos.setText("Telephone numbers:");

        lblFaxNo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblFaxNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFaxNo.setText("FAX number:");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email addresses:");

        lblSsn.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblSsn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSsn.setText("Social Security number:");

        lblMedicalRecNum.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblMedicalRecNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicalRecNum.setText("Medical record number:");

        lblHealthPlanNum.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblHealthPlanNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHealthPlanNum.setText("Health plan beneficiary number:");

        lblBankAcc.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblBankAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBankAcc.setText("Bank account numbers:");

        lblLicenseNo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblLicenseNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLicenseNo.setText("Certificate/license number:");

        lblVehicleIden.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblVehicleIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicleIden.setText("Vehicle identifiers and serial numbers including license plates:");

        lblDeviceIden.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblDeviceIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeviceIden.setText("Internet protocol addresses:");

        lblLinkedIn.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblLinkedIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLinkedIn.setText("Biometric identifiers (i.e. retinal scan, fingerprints):");

        lblIpAddress.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblIpAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIpAddress.setText("Device identifiers and serial numbers:");

        lblBiometric.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblBiometric.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBiometric.setText("LinkedIn:");

        lblUniqueIden.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblUniqueIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUniqueIden.setText("Any unique identifying number, characteristic, or code:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });

        txtLicenseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNoActionPerformed(evt);
            }
        });

        txtUniqueIden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueIdenActionPerformed(evt);
            }
        });

        lblImageDesc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        lblImageDesc.setText("Face Photo");

        lblBiometricDesc.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        lblBiometricDesc.setText("Biometric");

        llblCreate.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        llblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llblCreate.setText("View Panel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(llblCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIpAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeviceIden, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLinkedIn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txtBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBiometricDesc)
                            .addGap(123, 123, 123))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)
                            .addComponent(lblImageDesc)
                            .addGap(112, 112, 112))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTeleNos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMedicalRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHealthPlanNum, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblBiometricImage, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVehicleIden, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeviceIden, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(239, 239, 239))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblGeoData)
                        .addComponent(lblName)
                        .addComponent(lblDob)
                        .addComponent(lblTeleNos)
                        .addComponent(lblFaxNo)
                        .addComponent(lblEmail)
                        .addComponent(lblSsn)
                        .addComponent(lblMedicalRecNum)
                        .addComponent(lblHealthPlanNum)
                        .addComponent(lblBankAcc)
                        .addComponent(lblLicenseNo)
                        .addComponent(lblVehicleIden)
                        .addComponent(lblBiometric)
                        .addComponent(lblUniqueIden))
                    .addGap(18, 18, 18)
                    .addComponent(txtUniqueIden, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(llblCreate)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtName)
                        .addGap(18, 18, 18)
                        .addComponent(txtGeoData)
                        .addGap(11, 11, 11)
                        .addComponent(txtDob)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTeleNos)
                        .addGap(8, 8, 8))
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImageDesc)
                        .addGap(35, 35, 35)
                        .addComponent(lblBiometricImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBiometricDesc)
                        .addGap(291, 291, 291))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFaxNo)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail)
                        .addGap(18, 18, 18)
                        .addComponent(txtSsn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMedicalRecNum)
                        .addGap(18, 18, 18)
                        .addComponent(txtHealthPlanNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBankAcc)
                        .addGap(17, 17, 17)
                        .addComponent(txtLicenseNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVehicleIden)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeviceIden)
                            .addComponent(lblIpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(txtLinkedin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIpAddress)
                            .addComponent(lblDeviceIden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBiometric)
                            .addComponent(lblLinkedIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(19, 19, 19)
                            .addComponent(lblGeoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(19, 19, 19)
                            .addComponent(lblDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(19, 19, 19)
                            .addComponent(lblTeleNos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(19, 19, 19)
                            .addComponent(lblFaxNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(19, 19, 19)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(19, 19, 19)
                            .addComponent(lblSsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(19, 19, 19)
                            .addComponent(lblMedicalRecNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(19, 19, 19)
                            .addComponent(lblHealthPlanNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(19, 19, 19)
                            .addComponent(lblBankAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(19, 19, 19)
                            .addComponent(lblLicenseNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(14, 14, 14)
                            .addComponent(lblVehicleIden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(46, 46, 46)
                            .addComponent(lblBiometric, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(76, 76, 76)
                            .addComponent(lblUniqueIden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                            .addGap(575, 575, 575)
                            .addComponent(txtUniqueIden)))
                    .addGap(44, 44, 44)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtUniqueIdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueIdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueIdenActionPerformed

    private void txtLicenseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBankAcc;
    private javax.swing.JLabel lblBiometric;
    private javax.swing.JLabel lblBiometricDesc;
    private javax.swing.JLabel lblBiometricImage;
    private javax.swing.JLabel lblDeviceIden;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaxNo;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHealthPlanNum;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImageDesc;
    private javax.swing.JLabel lblIpAddress;
    private javax.swing.JLabel lblLicenseNo;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalRecNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTeleNos;
    private javax.swing.JLabel lblUniqueIden;
    private javax.swing.JLabel lblVehicleIden;
    private javax.swing.JLabel llblCreate;
    private javax.swing.JTextField txtBankAcc;
    private javax.swing.JTextField txtBiometric;
    private javax.swing.JTextField txtDeviceIden;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealthPlanNum;
    private javax.swing.JTextField txtIpAddress;
    private javax.swing.JTextField txtLicenseNo;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalRecNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTeleNos;
    private javax.swing.JTextField txtUniqueIden;
    private javax.swing.JTextField txtVehicleIden;
    // End of variables declaration//GEN-END:variables
}
